const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const packageDir = path.join(root, "dist", "ai-agent-debug-kit");
const zipPath = path.join(root, "dist", "ai-agent-debug-kit.zip");
const manifestPath = path.join(packageDir, "PACKAGE_MANIFEST.json");

assert.ok(fs.existsSync(packageDir), "release package folder is missing");
assert.ok(fs.existsSync(zipPath), "release zip is missing");
assert.ok(fs.statSync(zipPath).size > 1000, "release zip is unexpectedly small");
assert.ok(fs.existsSync(manifestPath), "package manifest is missing");

const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
assert.equal(manifest.name, "ai-agent-debug-kit");
assert.equal(manifest.version, "0.5.0");
assert.ok(manifest.files.includes("index.html"));
assert.ok(manifest.files.includes("SUPPORT.md"));
assert.ok(manifest.files.includes("robots.txt"));
assert.ok(manifest.files.includes("sitemap.xml"));
assert.ok(manifest.files.includes("extension/popup.html"));
assert.ok(manifest.files.includes("extension/core.js"));
assert.ok(manifest.files.includes("assets/agent-log-rescue-cover.svg"));
assert.ok(manifest.files.includes("assets/automation-failure-rescue-cover.svg"));
assert.ok(manifest.files.includes("assets/domestic-299-diagnosis-cover.png"));
assert.ok(manifest.files.includes("assets/domestic-299-diagnosis-cover.svg"));
assert.ok(manifest.files.includes("assets/domestic-299-diagnosis-proof.png"));
assert.ok(manifest.files.includes("assets/domestic-299-diagnosis-proof.svg"));
assert.ok(manifest.files.includes("assets/domestic-299-price-ladder.png"));
assert.ok(manifest.files.includes("assets/domestic-299-price-ladder.svg"));
assert.ok(manifest.files.includes("assets/domestic-299-diagnosis-one-pager.png"));
assert.ok(manifest.files.includes("assets/domestic-999-repair-plan-proof.png"));
assert.ok(manifest.files.includes("assets/automation-rescue-one-pager.pdf"));
assert.ok(manifest.files.includes("assets/automation-rescue-demo.gif"));
assert.ok(manifest.files.includes("assets/product-preview.svg"));
assert.ok(manifest.files.includes("docs/AI_WORKFLOW_COST_AUDIT_OFFER.md"));
assert.ok(manifest.files.includes("docs/BUG_REPORT_TRIAGE_OFFER.md"));
assert.ok(manifest.files.includes("docs/AEO_DELIVERY_CHECKLIST.md"));
assert.ok(manifest.files.includes("docs/AEO_OUTREACH_AND_QUOTE_PACK.md"));
assert.ok(manifest.files.includes("docs/AEO_READINESS_AUDIT_OFFER.md"));
assert.ok(manifest.files.includes("docs/AUTOMATION_FAILURE_RESCUE_OFFER.md"));
assert.ok(manifest.files.includes("docs/AUTOMATION_FAILURE_RESCUE_PROMO_PACK.md"));
assert.ok(manifest.files.includes("docs/CHINESE_BUYER_INTAKE_FORM.md"));
assert.ok(manifest.files.includes("docs/CHINESE_BUYER_CONVERSION_MESSAGES.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_SAMPLE_INTAKE_REPLY.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_30_MIN_DELIVERY_CHECKLIST.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_CUSTOM_OFFER_PACK.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_BUYER_REPLY_BUNDLE.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_QUOTE_DECISION_MATRIX.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_TO_999_UPSELL_HANDOFF.md"));
assert.ok(manifest.files.includes("docs/CHINESE_999_UPGRADE_REPLY_PACK.md"));
assert.ok(manifest.files.includes("docs/CHINESE_999_CUSTOM_OFFER_PACK.md"));
assert.ok(manifest.files.includes("docs/CHINESE_1999_RESCUE_RESCOPE_PACK.md"));
assert.ok(manifest.files.includes("docs/CHINESE_PACKAGE_LADDER_ONE_PAGER.md"));
assert.ok(manifest.files.includes("docs/CHINESE_BUYER_OBJECTION_HANDLING_PACK.md"));
assert.ok(manifest.files.includes("docs/CHINESE_OFFER_CARD_COPY.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_DIAGNOSIS_ONE_PAGER.md"));
assert.ok(manifest.files.includes("docs/CHINESE_AUTOMATION_RESCUE_POSTING_PACK.md"));
assert.ok(manifest.files.includes("docs/CHINESE_QUICK_DIAGNOSIS_LISTING.md"));
assert.ok(manifest.files.includes("docs/CHINESE_AEO_READINESS_LISTING.md"));
assert.ok(manifest.files.includes("docs/CLI_REFERENCE.md"));
assert.ok(manifest.files.includes("docs/CLIENT_DELIVERY_TEMPLATE.md"));
assert.ok(manifest.files.includes("docs/CLIENT_INTAKE_FORM.md"));
assert.ok(manifest.files.includes("docs/CLIENT_REQUEST_TRIAGE.md"));
assert.ok(manifest.files.includes("docs/CONTINUOUS_OPERATING_MODE.md"));
assert.ok(manifest.files.includes("docs/CUSTOM_OFFER_AUTOMATION_RESCUE.md"));
assert.ok(manifest.files.includes("docs/DEMO_SCRIPT.md"));
assert.ok(manifest.files.includes("docs/DOMESTIC_LEAD_TRIAGE_TRACKER.md"));
assert.ok(manifest.files.includes("docs/DOMESTIC_OUTREACH_SCRIPTS.md"));
assert.ok(manifest.files.includes("docs/DOMESTIC_299_UPLOAD_CHECKLIST.md"));
assert.ok(manifest.files.includes("docs/DOMESTIC_POSTING_BUNDLE.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_DOMESTIC_LISTING_PAGE.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_XHS_XIANYU_POSTS.md"));
assert.ok(manifest.files.includes("docs/CHINESE_DOMESTIC_POSTING_SCHEDULE.md"));
assert.ok(manifest.files.includes("docs/CHINESE_DOMESTIC_LEAD_SCORECARD.md"));
assert.ok(manifest.files.includes("docs/CHINESE_DOMESTIC_CHAT_REPLY_ROUTER.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_PAID_ORDER_HANDOFF.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_PAID_ORDER_LAUNCH_CHECKLIST.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_PAID_ORDER_TRACKER.md"));
assert.ok(manifest.files.includes("docs/CHINESE_FIRST_ORDER_DASHBOARD.md"));
assert.ok(manifest.files.includes("docs/CHINESE_FIRST_PAID_ORDER_RUNBOOK.md"));
assert.ok(manifest.files.includes("docs/CHINESE_FIRST_ORDER_HANDOFF_PROMPTS.md"));
assert.ok(manifest.files.includes("docs/CHINESE_BUYER_PRE_DIAGNOSIS_ASSET_COPY.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_EIGHT_IMAGE_POSTING_CAPTION.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_MOBILE_POSTING_CHECKLIST.md"));
assert.ok(manifest.files.includes("docs/CHINESE_299_24H_FOLLOW_UP_CADENCE.md"));
assert.ok(manifest.files.includes("docs/CHINESE_DAILY_LEAD_REVIEW_CHECKLIST.md"));
assert.ok(manifest.files.includes("assets/domestic-299-what-to-send.svg"));
assert.ok(manifest.files.includes("assets/domestic-299-what-to-send.png"));
assert.ok(manifest.files.includes("assets/domestic-299-do-not-send.svg"));
assert.ok(manifest.files.includes("assets/domestic-299-do-not-send.png"));
assert.ok(manifest.files.includes("assets/domestic-299-summary-card.svg"));
assert.ok(manifest.files.includes("assets/domestic-299-summary-card.png"));
assert.ok(manifest.files.includes("assets/ci-risk-gate-cover.svg"));
assert.ok(manifest.files.includes("assets/ci-risk-gate-cover.png"));
assert.ok(manifest.files.includes("assets/ci-risk-gate-sample-proof.png"));
assert.ok(manifest.files.includes("assets/ci-risk-gate-one-pager.pdf"));
assert.ok(manifest.files.includes("docs/EMERGENCY_AI_AUTOMATION_RESCUE_OFFER.md"));
assert.ok(manifest.files.includes("docs/FIVERR_ACTIVE_SOURCING.md"));
assert.ok(manifest.files.includes("docs/FIVERR_EXTERNAL_LINK_REPLY_PACK.md"));
assert.ok(manifest.files.includes("docs/FIVERR_GALLERY_ASSET_AUDIT.md"));
assert.ok(manifest.files.includes("docs/FIVERR_UPLOAD_HANDOFF.md"));
assert.ok(manifest.files.includes("docs/CI_RISK_GATE_ONE_PAGER.md"));
assert.ok(manifest.files.includes("docs/CI_RISK_GATE_BUYER_REPLY_PACK.md"));
assert.ok(manifest.files.includes("docs/CI_RISK_GATE_CHAT_HANDOFF.md"));
assert.ok(manifest.files.includes("docs/CI_RISK_GATE_BUYER_INTAKE_MINI_FORM.md"));
assert.ok(manifest.files.includes("docs/CI_RISK_GATE_BUYER_FAQ_AND_OBJECTIONS.md"));
assert.ok(manifest.files.includes("docs/CI_RISK_GATE_CUSTOM_OFFER_RUNBOOK.md"));
assert.ok(manifest.files.includes("docs/CI_RISK_GATE_CUSTOM_OFFER_CALCULATOR.md"));
assert.ok(manifest.files.includes("docs/CI_RISK_GATE_DELIVERY_TEMPLATE.md"));
assert.ok(manifest.files.includes("docs/CI_RISK_GATE_DELIVERY_QA_CHECKLIST.md"));
assert.ok(manifest.files.includes("docs/LAUNCH_STATUS.md"));
assert.ok(manifest.files.includes("docs/MICRO_PRODUCT_PACKS.md"));
assert.ok(manifest.files.includes("docs/MOBILE_STATUS.md"));
assert.ok(manifest.files.includes("docs/OPPORTUNITY_PIPELINE.md"));
assert.ok(manifest.files.includes("docs/PLATFORM_SETUP.md"));
assert.ok(manifest.files.includes("docs/PORTFOLIO_CASE_AUTOMATION_FAILURE_RESCUE.md"));
assert.ok(manifest.files.includes("docs/PORTFOLIO_CASE_AGENT_LOG_RESCUE.md"));
assert.ok(manifest.files.includes("docs/PORTFOLIO_CASE_CI_RISK_GATE.md"));
assert.ok(manifest.files.includes("docs/PORTFOLIO_CASE_PROMO_PACK.md"));
assert.ok(manifest.files.includes("docs/PRODUCT_PAGE.md"));
assert.ok(manifest.files.includes("docs/QUICK_DIAGNOSIS_OFFER.md"));
assert.ok(manifest.files.includes("docs/RESCUE_BUYER_BRIEF.md"));
assert.ok(manifest.files.includes("docs/SERVICE_OFFERS.md"));
assert.ok(manifest.files.includes("docs/UPLOAD_ASSET_CHECKLIST.md"));
assert.ok(manifest.files.includes("docs/VISUAL_ASSET_PRODUCTION_CHECKLIST.md"));
assert.ok(manifest.files.includes("docs/VIDEO_STORYBOARD_AUTOMATION_RESCUE.md"));
assert.ok(manifest.files.includes("docs/examples/agent-risk-gate.yml"));
assert.ok(manifest.files.includes("docs/examples/aeo-readiness-sample-report.md"));
assert.ok(manifest.files.includes("docs/examples/aeo-report-template.json"));
assert.ok(manifest.files.includes("docs/examples/aeo-readiness-sample-report.json"));
assert.ok(manifest.files.includes("docs/examples/automation-failure-rescue-report-template.md"));
assert.ok(manifest.files.includes("docs/examples/chinese-299-diagnosis-sample-report.md"));
assert.ok(manifest.files.includes("docs/examples/chinese-299-diagnosis-report-template.md"));
assert.ok(manifest.files.includes("docs/examples/chinese-999-repair-plan-template.md"));
assert.ok(manifest.files.includes("docs/examples/chinese-999-repair-plan-sample.md"));
assert.ok(manifest.files.includes("docs/examples/chinese-299-paid-order-tracker.csv"));
assert.ok(manifest.files.includes("docs/examples/ci-risk-gate-pass-log.jsonl"));
assert.ok(manifest.files.includes("docs/examples/ci-risk-gate-fail-log.jsonl"));
assert.ok(manifest.files.includes("docs/examples/ci-risk-gate-sample-pair.md"));
assert.ok(manifest.files.includes("docs/examples/domestic-lead-tracker.csv"));
assert.ok(manifest.files.includes("docs/examples/emergency-rescue-report-template.md"));
assert.ok(manifest.files.includes("docs/examples/webhook-json-mapping-demo-log.jsonl"));
assert.ok(manifest.files.includes("docs/examples/sample-report.md"));
assert.ok(manifest.files.includes("docs/examples/sample-report.json"));

console.log("Release validation passed");
